// ForeFlight CSV header -> model field maps (mirror of backend columns.py).
// Used by the in-browser importer for the no-backend preview demo.

export const AIRCRAFT_HEADER_TO_FIELD: Record<string, string> = {
  AircraftID: "aircraft_id",
  TypeCode: "type_code",
  Year: "year",
  Make: "make",
  Model: "model",
  GearType: "gear_type",
  EngineType: "engine_type",
  "equipType (FAA)": "equip_type",
  "aircraftClass (FAA)": "aircraft_class",
  "complexAircraft (FAA)": "complex",
  "taa (FAA)": "taa",
  "highPerformance (FAA)": "high_performance",
  "pressurized (FAA)": "pressurized",
};

export const FLIGHT_HEADER_TO_FIELD: Record<string, string> = {
  Date: "date",
  AircraftID: "aircraft_id",
  From: "from_",
  To: "to",
  Route: "route",
  TimeOut: "time_out",
  TimeOff: "time_off",
  TimeOn: "time_on",
  TimeIn: "time_in",
  OnDuty: "on_duty",
  OffDuty: "off_duty",
  TotalTime: "total_time",
  PIC: "pic",
  SIC: "sic",
  Night: "night",
  Solo: "solo",
  CrossCountry: "cross_country",
  PICUS: "picus",
  MultiPilot: "multi_pilot",
  IFR: "ifr",
  Examiner: "examiner",
  NVG: "nvg",
  "NVG Ops": "nvg_ops",
  Distance: "distance",
  ActualInstrument: "actual_instrument",
  SimulatedInstrument: "simulated_instrument",
  HobbsStart: "hobbs_start",
  HobbsEnd: "hobbs_end",
  TachStart: "tach_start",
  TachEnd: "tach_end",
  Holds: "holds",
  Approach1: "approach1",
  Approach2: "approach2",
  Approach3: "approach3",
  Approach4: "approach4",
  Approach5: "approach5",
  Approach6: "approach6",
  DualGiven: "dual_given",
  DualReceived: "dual_received",
  SimulatedFlight: "simulated_flight",
  GroundTraining: "ground_training",
  GroundTrainingGiven: "ground_training_given",
  InstructorName: "instructor_name",
  InstructorComments: "instructor_comments",
  Person1: "person1",
  Person2: "person2",
  Person3: "person3",
  Person4: "person4",
  Person5: "person5",
  Person6: "person6",
  PilotComments: "pilot_comments",
  "Flight Review (FAA)": "flight_review",
  "IPC (FAA)": "ipc",
  "Checkride (FAA)": "checkride",
  "FAA 61.58 (FAA)": "faa_6158",
  "NVG Proficiency (FAA)": "nvg_proficiency",
  DayTakeoffs: "day_takeoffs",
  DayLandingsFullStop: "day_landings_full_stop",
  NightTakeoffs: "night_takeoffs",
  NightLandingsFullStop: "night_landings_full_stop",
  AllLandings: "all_landings",
};
